function patch_vertices = TilePatch(centerX, centerY, normal, min_edge_radius)
    r = min_edge_radius;
    s = r / cosd(30);

    elev = normal(2);
    azim = normal(3);
    
    patch_vertices = [...   % List of vertices in CCW order, starting w/ point @ "0 deg"
        ... % Point 1
        centerX + s*cosd(azim), ...
        centerY, ...
        -(s * sind(azim));...
        ... % Point 2
        centerX + (s/2)*cosd(azim), ...
        centerY + r * cosd(abs(elev)), ...
        -(s/2)*sind(azim) - r*sind(elev);...
        ... % Point 3
        centerX - (s/2)*cosd(azim), ...
        centerY + r * cosd(abs(elev)), ...
        (s/2)*sind(azim) - r*sind(elev);...
        ... % Point 4
        centerX - s*cosd(azim), ...
        centerY, ...
        s * sind(azim);...
        ... % Point 5
        centerX - (s/2)*cosd(azim), ...
        centerY - r * cosd(abs(elev)), ...
        (s/2)*sind(azim) + r*sind(elev);...
        ... % Point 6
        centerX + (s/2)*cosd(azim), ...
        centerY - r * cosd(abs(elev)), ...
        -(s/2)*sind(azim) + r*sind(elev);...
    ];
    
    face = [1 2 3 4 5 6];
    
    patch('Faces', face, 'Vertices', patch_vertices, 'Facecolor', [0.8 0.8 1]);
    view(3);
end